#
# Makefile for development
#

PY_SRC_PATH=$(HOME)/projects/yjw/python

RASMUS_SRC_FILES = __init__ \
		   tablelib \
                   timer \
		   treelib \
                   treelib_parser \
                   treelib_lex \
                   treelib_tab \
                   stats \
                   util

RASMUS_PLY_FILES = README \
                   __init__.py \
                   lex.py \
	           yacc.py

COMPBIO_SRC_FILES = __init__ \
                    fasta \
		    phylo \
		    seqlib

VERSIONS = versions.txt

# all
all: includepy 

# copy subset of python modules for packaging with treefix
includepy: versions
	mkdir -p python/raxml/deps/rasmus
	for mod in $(RASMUS_SRC_FILES); do \
		cp $(PY_SRC_PATH)/rasmus/$${mod}.py python/raxml/deps/rasmus/$${mod}.py; \
	done

	mkdir -p python/raxml/deps/rasmus/ply
	for mod in $(RASMUS_PLY_FILES); do \
	 	cp $(PY_SRC_PATH)/rasmus/ply/$${mod} python/raxml/deps/rasmus/ply/$${mod}; \
	done

	mkdir -p python/raxml/deps/compbio
	for mod in $(COMPBIO_SRC_FILES); do \
		cp $(PY_SRC_PATH)/compbio/$${mod}.py python/raxml/deps/compbio/$${mod}.py; \
	done

# copy versions
versions:
	touch $(VERSIONS)

	echo -ne "rasmus\t" > $(VERSIONS)
	cd $(PY_SRC_PATH)/rasmus; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

	echo -ne "compbio\t" >> $(VERSIONS)
	cd $(PY_SRC_PATH)/compbio; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

# clean
clean:
	rm versions.txt
	rm python/raxml/*.pyc
	rm -r python/raxml/deps

