#
# Makefile for development
#

PY_SRC_PATH=$(HOME)/projects/yjw/python

RASMUS_SRC_FILES = __init__ \
		   tablelib \
		   timer \
		   treelib \
		   stats \
		   util \
		   textdraw \

COMPBIO_SRC_FILES = __init__ \
		    fasta \
		    phylo \
		    seqlib \
		    alignlib \
		    phylip

VERSIONS = versions.txt

# all
all: includepy

# copy subset of python modules for packaging with treefix
includepy: versions
	mkdir -p python/treefix/deps/rasmus
	for mod in $(RASMUS_SRC_FILES); do \
		cp $(PY_SRC_PATH)/rasmus/$${mod}.py python/treefix/deps/rasmus/$${mod}.py; \
	done

	mkdir -p python/treefix/deps/compbio
	for mod in $(COMPBIO_SRC_FILES); do \
		cp $(PY_SRC_PATH)/compbio/$${mod}.py python/treefix/deps/compbio/$${mod}.py; \
	done

# copy versions
versions:
	touch $(VERSIONS)

	echo -ne "rasmus\t" > $(VERSIONS)
	cd $(PY_SRC_PATH)/rasmus; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

	echo -ne "compbio\t" >> $(VERSIONS)
	cd $(PY_SRC_PATH)/compbio; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

# clean
clean:
	rm versions.txt
	rm python/treefix/*.pyc
	rm python/treefix/models/*.pyc
	rm -r python/treefix/deps

